package maquinadecafe;


public class TelaMaquinaDeCafe extends javax.swing.JFrame {

    /**
     * Creates new form TelaMaquinaDeCafe
     */
    ControlarMaquina Controle = new ControlarMaquina();
    private float saldo = 0;
    private String resultado;

    public TelaMaquinaDeCafe() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botao_estado = new javax.swing.JButton();
        botao_capuccino = new javax.swing.JButton();
        botao_cafecleite = new javax.swing.JButton();
        botao_cafe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texto_dinheiro = new javax.swing.JTextField();
        texto_Estado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("MAQUINA DE CAFÉ");

        botao_estado.setText("ON/OFF");
        botao_estado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_estadoActionPerformed(evt);
            }
        });

        botao_capuccino.setText("Capuccino");
        botao_capuccino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_capuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_capuccinoActionPerformed(evt);
            }
        });

        botao_cafecleite.setText("Cafe com Leite");
        botao_cafecleite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_cafecleite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cafecleiteActionPerformed(evt);
            }
        });

        botao_cafe.setText("Cafe ");
        botao_cafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cafeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Tipos de Cafe");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Valor R$:");

        texto_dinheiro.setText("0,00");

        texto_Estado.setText("OFF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(texto_dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botao_capuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botao_cafecleite, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(botao_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(botao_estado)
                                .addGap(18, 18, 18)
                                .addComponent(texto_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao_estado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_cafe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_cafecleite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_capuccino)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_estadoActionPerformed
        // TODO add your handling code here:
         texto_dinheiro.setText("0,00");
         texto_Estado.setText("ON");
         
         if (Controle.isLigada() == true){
             texto_Estado.setText("OFF");
             Controle.desligar();
             saldo = 0;
             
         }else{
         Controle.ligar();
         }
    }//GEN-LAST:event_botao_estadoActionPerformed

    private void botao_cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cafeActionPerformed
        // TODO add your handling code here:
        if(Controle.isLigada() == true){
        saldo += 1.00;
        resultado = String.valueOf(saldo);
        texto_dinheiro.setText(resultado);
        }
    }//GEN-LAST:event_botao_cafeActionPerformed

    private void botao_cafecleiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cafecleiteActionPerformed
        // TODO add your handling code here:
        if(Controle.isLigada()==true){
        saldo += 1.50;
        resultado = String.valueOf(saldo);
        texto_dinheiro.setText(resultado);
        }
    }//GEN-LAST:event_botao_cafecleiteActionPerformed

    private void botao_capuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_capuccinoActionPerformed
        // TODO add your handling code here:
        if(Controle.isLigada()== true){
        saldo += 2.00;
        resultado = String.valueOf(saldo);
        texto_dinheiro.setText(resultado);
        }
    }//GEN-LAST:event_botao_capuccinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaquinaDeCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaquinaDeCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaquinaDeCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaquinaDeCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new TelaMaquinaDeCafe().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cafe;
    private javax.swing.JButton botao_cafecleite;
    private javax.swing.JButton botao_capuccino;
    private javax.swing.JButton botao_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField texto_Estado;
    private javax.swing.JTextField texto_dinheiro;
    // End of variables declaration//GEN-END:variables
}
